### ISSUE TITLE
Panic on deserialization 

### ISSUE THREAD

**Issue by Cravtos** [ralexstokes/ssz_rs#7]
I was trying to write test cases for https://github.com/ralexstokes/ethereum_consensus to check if operations work correctly, but faced problems with the deserialization of `BeaconBlock` from `block.ssz_snappy`

Here is code for reproducing panic:
```rust
use ethereum_consensus::phase0::mainnet::BeaconBlock;
use project_root;
use snap;
use ssz_rs::prelude::*;
use std::fs::File;
use std::io::Read;
use std::path::Path;
use std::path::PathBuf;

#[test]
fn test_invalid_parent_root() {
    let path = Path::new("consensus-spec-tests/tests/mainnet/phase0/operations/block_header/pyspec_tests/invalid_parent_root/");

    let block_path = path.join("block.ssz_snappy");
    let block_path = block_path.to_str().expect("is valid path");

    let block_data = read_ssz_snappy_from_test_data(block_path);
    println!("block data from file {:?}", block_data);

    // for clarity
    let default_block = BeaconBlock::default();
    let ser_default_block = ssz_rs::serialize(&default_block).expect("can serialize");
    println!("default block data {:?}", ser_default_block);

    let block: BeaconBlock = ssz_rs::deserialize(&block_data).expect("can deserialize");
    println!("block from file {:?}", block);
}

// Return SSZ-encoded bytes from test file at `target_path`
pub fn read_ssz_snappy_from_test_data(target_path: &str) -> Vec<u8> {
    let project_root = project_root::get_project_root().unwrap();
    let target_path = PathBuf::from(target_path);
    let data_path = project_root.join(&target_path);
    let mut file = File::open(&data_path).expect("can read file");
    let mut data = vec![];
    let _ = file.read_to_end(&mut data).expect("can read file data");
    let mut decoder = snap::raw::Decoder::new();
    decoder
        .decompress_vec(&data)
        .expect("can decompress snappy")
}
```

Output:

```bash
block data from file [1, 0, 0, 0, 0, 0, 0, 0, 174, 0, 0, 0, 0, 0, 0, 0, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 84, 0, 0, 0, 132, 104, 188, 10, 245, 110, 113, 55, 111, 77, 65, 137, 20, 99, 112, 142, 241, 25, 41, 49, 219, 43, 36, 235, 53, 18, 216, 51, 83, 152, 0, 250, 94, 3, 9, 107, 173, 249, 30, 84, 252, 0, 232, 139, 156, 254, 184, 37, 18, 253, 41, 181, 18, 160, 148, 212, 215, 136, 104, 3, 185, 127, 64, 10, 147, 134, 151, 134, 219, 131, 237, 40, 151, 198, 107, 90, 44, 119, 157, 111, 151, 200, 255, 110, 221, 150, 109, 13, 144, 129, 255, 201, 55, 90, 18, 40, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 220, 0, 0, 0, 220, 0, 0, 0, 220, 0, 0, 0, 220, 0, 0, 0, 220, 0, 0, 0]
default block data [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 84, 0, 0, 0, 192, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 220, 0, 0, 0, 220, 0, 0, 0, 220, 0, 0, 0, 220, 0, 0, 0, 220, 0, 0, 0]
thread 'test_invalid_parent_root' panicked at 'range end index 4 out of range for slice of length 0', /home/cravtos/.cargo/git/checkouts/ssz_rs-4493665f49c79d5a/7a29e15/ssz_rs/src/de.rs:50:42
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::slice::index::slice_end_index_len_fail
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/slice/index.rs:41:5
   3: <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/slice/index.rs:240:13
   4: <core::ops::range::RangeTo<usize> as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/slice/index.rs:286:9
   5: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/slice/index.rs:15:9
   6: ssz_rs::de::deserialize_variable_homogeneous_composite
             at /home/cravtos/.cargo/git/checkouts/ssz_rs-4493665f49c79d5a/7a29e15/ssz_rs/src/de.rs:50:42
   7: ssz_rs::de::deserialize_homogeneous_composite
             at /home/cravtos/.cargo/git/checkouts/ssz_rs-4493665f49c79d5a/7a29e15/ssz_rs/src/de.rs:78:9
   8: <ssz_rs::list::List<T,_> as ssz_rs::de::Deserialize>::deserialize
             at /home/cravtos/.cargo/git/checkouts/ssz_rs-4493665f49c79d5a/7a29e15/ssz_rs/src/list.rs:142:22
   9: ethereum_consensus::phase0::beacon_block::BeaconBlockBody<_,_,_,_,_,_>::__ssz_rs_set_by_index
             at ./src/phase0/beacon_block.rs:21:5
  10: <ethereum_consensus::phase0::beacon_block::BeaconBlockBody<_,_,_,_,_,_> as ssz_rs::de::Deserialize>::deserialize
             at ./src/phase0/beacon_block.rs:8:26
  11: ethereum_consensus::phase0::beacon_block::BeaconBlock<_,_,_,_,_,_>::__ssz_rs_set_by_index
             at ./src/phase0/beacon_block.rs:41:5
  12: <ethereum_consensus::phase0::beacon_block::BeaconBlock<_,_,_,_,_,_> as ssz_rs::de::Deserialize>::deserialize
             at ./src/phase0/beacon_block.rs:28:26
  13: ssz_rs::deserialize
             at /home/cravtos/.cargo/git/checkouts/ssz_rs-4493665f49c79d5a/7a29e15/ssz_rs/src/lib.rs:62:5
  14: operations_tests::test_invalid_parent_root
             at ./tests/operations_tests.rs:41:30
  15: operations_tests::test_invalid_parent_root::{{closure}}
             at ./tests/operations_tests.rs:27:1
  16: core::ops::function::FnOnce::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
  17: core::ops::function::FnOnce::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
```

Same panic if I try to deserialize serialized `BeaconBlock::default()`

**Comment by ralexstokes** [comment]
i tracked this down to an issue w/ deserializing nested lists and fixed in: https://github.com/ralexstokes/ssz_rs/commit/658c5725e3b0cee313bc58ba2bfccd2c5f6cf90e

the problem here was deserializing the empty block body with an empty list of `Attestation` which are "variably sized" objects

this repo before this commit only handled this case appropriately with "fixed sized" objects
